#! /bin/sh

# bspwm setup
bspc monitor -d I II III IV V VI VII VIII IX
#xrandr --output eDP-1 --mode 2560x1440 --rotate normal --output HDMI-1-0 --mode 1920x1080 --rotate normal --right-of eDP-1
#bspc monitor HDMI-1-0 -d I II III IV V
#bspc monitor eDP-1 -d VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 30
bspc config left_padding 4
bspc config right_padding 4
bspc config border_radius 10

bspc config focused_border_color "#FFB800"
bspc config active_border_color "#272829"
bspc config normal_border_color "#272829"

# Rules (use xprop | grep WM_CLASS for window name)
bspc rule -a Analitica desktop='^6' follow=on
bspc rule -a Spotify desktop='^3'
bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Other setups

# cursor
xsetroot -cursor_name left_ptr &

# compositor
killall -q picom; picom --experimental-backends --config ~/.config/picom/picom.conf &

# sxhkd (Hot Key Daemon)
killall -q sxhkd; sxhkd &

# dunst (Notification Daemon)
killall -q dunst; dunst -conf ~/.config/dunst/dunstrc &

# polybar
~/.config/polybar/launch.sh &

# wallpaper
feh --bg-max --randomize ~/Pictures/Wallpaper/TCX/* &
